bounswe/bounswe2022group1

- practice-app/practiceapp/practiceapp/create_db.py
Database is created.
Dummy insertions is done.
All necessary things related to database is done.
> Database related issues

- practice-app/practiceapp/practiceapp/create_db.py
- practice-app/practiceapp/practiceapp/drop.py
> all up to date initial page, omer ozdemir change

- practice-app/README.md
- practice-app/practiceapp/learningPlatform/urls.py
bugfixes on urls file / and read.me
> bugfix on urls and readme

- practice-app/practiceapp/learningPlatform/templates/json.html
- practice-app/practiceapp/learningPlatform/templates/student_my_courses.html
- practice-app/practiceapp/learningPlatform/urls.py
- practice-app/practiceapp/learningPlatform/views/student_my_courses.py
- practice-app/requirements.txt
Osman added restfullness to his API. In order other team members to inspect that easily, I am pulling this changes to Master branch.
> Osman student mycourses

- practice-app/practiceapp/learningPlatform/static/styles.css
- practice-app/practiceapp/learningPlatform/templates/login.html
- practice-app/practiceapp/learningPlatform/tests.py
- practice-app/practiceapp/learningPlatform/tests/test_authentication.py
- practice-app/practiceapp/learningPlatform/urls.py
- practice-app/practiceapp/learningPlatform/views/authentication.py
I updated login page. I added REST API methods, unittests and external API. Main functionality of login page is preserved.
> Login logout mustafa atay

- practice-app/practiceapp/learningPlatform/static/styles.css
- practice-app/practiceapp/learningPlatform/templates/student_specify_preferences.html
- practice-app/practiceapp/learningPlatform/tests/test_specify_preferences.py
- practice-app/practiceapp/learningPlatform/urls.py
- practice-app/practiceapp/learningPlatform/views/student_specify_preferences.py
- I have added the unit tests for the API's written by me. 
- More tests will be added in the future.
> Ege student search course - API Tests are added.

- practice-app/practiceapp/learningPlatform/tests.py
- practice-app/practiceapp/learningPlatform/tests/test_student_my_courses.py
- practice-app/practiceapp/learningPlatform/urls.py
- practice-app/practiceapp/learningPlatform/views/student_my_courses.py
Pull request to master,
Review needed
> Osman student-mycourses

- practice-app/practiceapp/learningPlatform/tests/test_specify_preferences.py
- practice-app/practiceapp/learningPlatform/views/sign_up.py
- practice-app/practiceapp/learningPlatform/views/teacher_my_courses.py
-  Added a one more unit test for specify preferences
- Bug fixed by removing windows.asyncio events.
> Added one more unit test and bugfix

- practice-app/practiceapp/learningPlatform/templates/teacher_my_courses.html
- practice-app/practiceapp/learningPlatform/tests/test_teacher_my_courses.py
- practice-app/practiceapp/learningPlatform/urls.py
- practice-app/practiceapp/learningPlatform/views/teacher_my_courses.py
> post method and tests are created and external api is fixed for teacher_my_courses

- practice-app/practiceapp/learningPlatform/views/student_give_rate.py
I revised the APIs that I have implemented, can someone review and merge? I only made changes in student_give_rate.py.
> Efekan - Update on get and post

- practice-app/practiceapp/learningPlatform/tests/test_teacher_delete.py
- practice-app/practiceapp/learningPlatform/views/teacher_delete_course.py
updated since testcases didnt work
> updated for testcases

- practice-app/practiceapp/learningPlatform/tests/test_student_give_rate.py
I had some problems with the unit testing, now my tests are working. I would be thankful if someone can review and merge this to master.
> Give Rate: Unit Tests Added

- practice-app/practiceapp/learningPlatform/views/sign_up.py
I detected some error in my code. I fixed and tested, seems no problem.
> sign_up page bugfix

- practice-app/practiceapp/learningPlatform/urls.py
- practice-app/practiceapp/learningPlatform/views/teacher_add_course.py
> teacher_add_course for postman changes.

- practice-app/Dockerfile
- practice-app/docker-compose.yml
- practice-app/practiceapp/learningPlatform/views/authentication.py
- practice-app/practiceapp/learningPlatform/views/sign_up.py
- practice-app/practiceapp/learningPlatform/views/student_my_courses.py
- practice-app/practiceapp/learningPlatform/views/student_specify_preferences.py
- practice-app/practiceapp/learningPlatform/views/teacher_add_course.py
- practice-app/practiceapp/learningPlatform/views/teacher_delete_course.py
- practice-app/practiceapp/learningPlatform/views/teacher_my_courses.py
- practice-app/practiceapp/practiceapp/settings.py
Docker files are added. 
Bugs fixed. 
Made ready for deploy.
> Docker Files are added

- practice-app/practiceapp/learningPlatform/tests/test_teacher_add_course.py
- practice-app/practiceapp/learningPlatform/views/teacher_add_course.py
> LAST CHANGES OVER TEACHER ADD COURSE

- practice-app/practiceapp/learningPlatform/tests/test_student_my_courses.py
I fixed some bugs for the deployment
> Bug fixes for deployment

- practice-app/practiceapp/learningPlatform/tests/test_authentication.py
I fixed a bug we encountered in deployment in my unittests.
> bug fix in authentication tests

- practice-app/practiceapp/learningPlatform/views/student_give_rate.py
A control is added in case the external api is down
> Check for the external api

- practice-app/practiceapp/learningPlatform/views/authentication.py
I fixed an issue about external API usage of login page. Error conditions of external API response hadn't considered very well. That was causing an error in the page.
> External API error handling bug fix

- practice-app/practiceapp/learningPlatform/views/sign_up.py
There was no error handling for failure of external API. So, I have modified my code to handle it.
> external_api status code is checked

- README.md
I changed the course name and the name of the instructor.
> Changes according to the new term

- README.md
Added Huseyin and Kadir K to the Team Members.
Firstly, i could not find the github account of Huseyin. I would like to add Huseyin and Kadir as reviewers. When @kkadirkkalkan and Hüseyin finish the personal page, could you accept this PR?
*Reviewer:*  @kkadirkkalkan and @egetaga 
*PR Deadline:* 15.10.2022 15.00
Final Actions:
- Accept the PR
> addition of newcomers

- backend/app/serializers.py
- backend/app/urls.py
- backend/app/views.py
I have implemented login and logout functionalities together with change password functionality. I followed [this tutorial](https://studygyaan.com/django/django-rest-framework-tutorial-register-login-logout) and used django-rest-knox since it provides very easy to use authorization and authentication functionalities.
> Backend-dev login-logout functionalities

- backend/app/tests.py
- backend/app/tests/test_login.py
- backend/app/tests/test_logout.py
- backend/app/tests/test_register.py
I have added Django unit tests for login, logout and registration. All tests work fine and nicely. Would be glad if my PR is accepted.
> Added test cases for login, logout, register

- deliverables/CMPE451_Customer_Presentation_Milestone_1/Customer_Milestone_1.md
`Description:`  Individual reports are added into the repository.
> milestone 1 report added

- README.md
Also added building Django app part
> Added the deleted readme.md

- deliverables/CMPE451_Customer_Presentation_Milestone_1/Customer_Milestone_1.md
All the contributions are updated now.
> All the contributions are added

- deliverables/CMPE451_Customer_Presentation_Milestone_1/individual contribution reports/Kadir_Kalkan.md
My individual contribution report is added
> My individual contribution report is added

- deliverables/CMPE451_Customer_Presentation_Milestone_1/Customer_Milestone_1.md
I have added the group review wiki's contents to this document. Our master branch is protected, making writing directly to the master cumbersome. So, we have collected our work in https://github.com/bounswe/bounswe2022group1/wiki/CMPE451-Group-Review-(Milestone-1) and now adding to the master.
Please accept the PR.
> Added the group review

- backend/app/tests/test_change_password.py
- backend/app/tests/test_login.py
- backend/app/views.py
ChangePassword views is updated and change password unit test is added
> change password unit test is added

- backend/app/serializers.py
- backend/app/views.py
**To**
@egetaga @kkadirkkalkan 
**Description**
I implemented the patch method for Content API View. Thanks to that method, we can update fields of an existing Content. Besides that, while implementing this, I learned how updating partial fields work with serializers in Django. This PR will shed light on our further patch method implementations for other views.
**Testing**
User-tested via Postman.
Note: unittests will be added.
> Backend Content Update Api 

- backend/app/urls.py
- backend/app/views.py
- Implemented an API for listing all learning spaces, the end-point is app/learning-space-list/. You should send an authorized empty get request to access
- Implemented an API for searching in learning spaces, the end-point is app/learning-space-search/, you should send a get request with specifying search_parameter. Your request should be authorized.
> Implemented an APIs searching and listing all Learning Spaces

- backend/app/urls.py
- backend/app/views.py
We will employ tag searching for finding learning spaces. For that end, I have written a get api for tag searching. The endpoint is 'app/learning-space-tag-search/'.  You should request with specifying "tag" and you should be authorized.
> Implemented tag search functionality

- backend/app/helpers.py
- backend/app/serializers.py
- backend/app/urls.py
- backend/app/views.py
- backend/budemi/settings.py
The POST method to reset password is created. POST method requires an email. Random created new email will be sent to user, if a user exists with this email
> Password reset

- backend/app/views.py
User should register with a valid and unique email in order to user reset password functionality.
> Bug fix: valid and unique email

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/myapplication/model/change_password_failure_model.kt
- android/app/src/main/java/com/example/myapplication/model/change_password_response_model.kt
- android/app/src/main/java/com/example/myapplication/service/changePasswordApiCall.kt
- android/app/src/main/java/com/example/myapplication/service/change_password_api.kt
- android/app/src/main/java/com/example/myapplication/view/ChangePasswordActivity.kt
- android/app/src/main/java/com/example/myapplication/view/HomeActivity.kt
- android/app/src/main/java/com/example/myapplication/view/ProfilePageActivity.kt
- android/app/src/main/res/layout/activity_home.xml
- android/app/src/main/res/layout/activity_profilepage.xml
Change password functionality implemented and connected to the backend.
An issue about passing headers solved for further implementations.
> Change Password implemented, headers added to requests

- backend/app/urls.py
- backend/app/views.py
Leave learning space and get enrolled learning spaces APIs are written. With these new features user can leave a learning space and get previously enrolled learning spaces.
> Leave learning space and get enrolled learning spaces

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/myapplication/model/list_elements.kt
- android/app/src/main/java/com/example/myapplication/model/ls_by_tag_model.kt
- android/app/src/main/java/com/example/myapplication/model/ls_create_model.kt
- android/app/src/main/java/com/example/myapplication/model/ls_create_response_model.kt
- android/app/src/main/java/com/example/myapplication/model/ls_members.kt
- android/app/src/main/java/com/example/myapplication/service/ls_by_tag_api.kt
- android/app/src/main/java/com/example/myapplication/service/ls_by_tag_call.kt
- android/app/src/main/java/com/example/myapplication/service/ls_create_api.kt
- android/app/src/main/java/com/example/myapplication/service/ls_create_call.kt
- android/app/src/main/java/com/example/myapplication/view/ChangePasswordActivity.kt
- android/app/src/main/java/com/example/myapplication/view/HomeActivity.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace1.kt
- android/app/src/main/res/layout/add_learning_space.xml
- android/app/src/main/res/layout/learning_space_1.xml
I implemented change password functionality.
I set primary categories of learning spaces. According to this categories learning spaces will be listed.
Then user is redirected to the chosen learning space.
> Change Password and Learning Spaces

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/myapplication/view/AddContent.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace1.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace2.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace3.kt
- android/app/src/main/res/layout/activity_add_content.xml
- android/app/src/main/res/values/strings.xml
- Some bugs in the learning space 2 is fixed.
> learningSpace2, topic click lands content page

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/myapplication/view/LearningSpace1.kt
I passed a members list for displaying on the learning space page.
> Android: Members parameters passed for learning space

- android/app/src/main/java/com/example/myapplication/model/learningSpace2Leave_response_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3GetDiscussionList_send_model.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace2GetEnrolledLearningSpaces_api_call.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace2Leave_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace2Leave_api_call.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace2ListEveryLearningSpace_api_call.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3GetDiscussionList_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3GetDiscussionList_api_call.kt
- android/app/src/main/java/com/example/myapplication/service/resetPassword_api.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace2.kt
- android/app/src/main/res/layout/activity_add_content.xml
- Enroll page works flawlessly
- Discussion APIs are connected
- Bug fix for leave api
> New back-end connections for android and some bug fixes.

- android/app/src/main/java/com/example/myapplication/model/profile_edit_post_send_model.kt
- android/app/src/main/java/com/example/myapplication/view/AddContent.kt
- android/app/src/main/res/layout/activity_add_content.xml
`Description: ` Current design of the add content page is the following.
> Some design changes for add content

- frontend/src/components/detail/DetailPage.css
- frontend/src/components/detail/DetailPage.js
- frontend/src/components/login/login.js
- frontend/src/components/signup/signup.js
I have implemented add content dropdown button and join button to the detail page.
> adding addcontent dropdown and join button

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/myapplication/service/ls_search_api.kt
- android/app/src/main/java/com/example/myapplication/service/ls_search_api_call.kt
- android/app/src/main/java/com/example/myapplication/view/HomeActivity.kt
- android/app/src/main/java/com/example/myapplication/view/LsSearchActivity.kt
- android/app/src/main/res/drawable/search_view_bg.xml
- android/app/src/main/res/layout/activity_home.xml
- android/app/src/main/res/layout/activity_ls_search.xml
Search functionality added.
Functioning well.
> LS Search Implemented

- backend/app/tests/test_content.py
- backend/app/tests/test_content_list.py
- backend/app/tests/test_enroll.py
- backend/app/tests/test_learning_space.py
**To**
@egetaga @kkadirkkalkan 
**Description**
I wrote unit tests of the following endpoints:
- Learning Space
- Content
- Content List
- Enroll
> Backend tests

- backend/app/tests/test_enrolled_learning_spaces.py
- backend/app/tests/test_leave_learning_space.py
I wrote unit tests of the following endpoints:
- Get Enrolled Learning Spaces
- Leave Learning Space
> enrolled learning spaces and leave learning space tests are written

- backend/app/tests/test_discussion.py
- backend/app/tests/test_discussion_list.py
- backend/app/tests/test_learning_space_list.py
- backend/app/tests/test_learning_space_search.py
- backend/app/tests/test_learning_space_tag_search.py
I have prepared unit tests for: 
- discussion
- discussion list
- learning space list
- search with parameter
- search with tag
Please approve my PR.
> I have prepared tests for discussion and search

- deliverables/CMPE451_Customer_Presentation_Milestone_2/android/app/.idea/.gitignore
- deliverables/CMPE451_Customer_Presentation_Milestone_2/android/app/.idea/gradle.xml
- deliverables/CMPE451_Customer_Presentation_Milestone_2/android/app/.idea/misc.xml
- deliverables/CMPE451_Customer_Presentation_Milestone_2/android/app/src/main/java/com/example/myapplication/service/profile_edit_api.kt
- deliverables/CMPE451_Customer_Presentation_Milestone_2/android/app/src/main/java/com/example/myapplication/view/ProfileCreateActivity.kt
Somehow we put wrong android folder into the deliverables folder inside the android. The android folder inside the milestone2 and the android folder inside the master are the same now.
> milestone2 bug fix

- frontend/Dockerfile
As can be seen on[#653](https://github.com/bounswe/bounswe2022group1/issues/653), i need to change the Dockerfile because of the migration from ReactJS to NextJS.
> Docker file updated

- frontend/README.md
**PR Description:**
Commands of how to install dependencies, how to build and how to run the project are added to the README file.
> Commands of the nextjs is added

- deliverables/CMPE451_Customer_Presentation_Milestone_2/group_milestone_review.md
I have added the group review from the link https://github.com/bounswe/bounswe2022group1/wiki/Customer-Milestone-2-Group-Review. Please approve the PR.
> Added group review

- deliverables/CMPE451_Customer_Presentation_Milestone_2/group_milestone_review.md
Added Kadir Kalkan's individual contributions. Please approve the PR.
> Added Kadir Kalkan's individual contributions

- deliverables/CMPE451_Customer_Presentation_Milestone_2/group_milestone_review.md
Added Kadir's latest change on postman. Please approve the PR.
> Added Kadirs latest change

- deliverables/CMPE451_Customer_Presentation_Milestone_2/group_milestone_review.md
I added my own pull request and issue titles in tabular format.
> Summary of work in tabular format is added

- frontend/components/addcontent/AddContentInfoPage.js
- frontend/components/addcontent/ContentAdd.js
- frontend/components/detail/DetailMain.js
- frontend/pages/addcontent/[id]/[type].js
I have implemented add content menu. If text or meeting is clicked, name and text fields are displayed. If video or image is clicked, name and url textfields are displayed. Screenshots can be found at [this issue](https://github.com/bounswe/bounswe2022group1/issues/683)
> add content functionality is added

- android/app/src/main/res/layout/activity_sign_in.xml
- android/app/src/main/res/layout/activity_sign_up.xml
I changed sign-in and sign-up pages for better UI/UX experience. The following illustrates the new design.
**Photos:**
*Reviewer:* 
@gecemavisioa 
@acyishere  
*Review Deadline:*
17.12.2022
> Sign-in and Sign-up design changes.

- android/app/src/main/java/com/example/myapplication/model/list_element_user.kt
- android/app/src/main/java/com/example/myapplication/model/profile_see_get_receive_model.kt
- android/app/src/main/java/com/example/myapplication/view/ForgotPasswordActivity.kt
- android/app/src/main/java/com/example/myapplication/view/HomeActivity.kt
- android/app/src/main/java/com/example/myapplication/view/LandingActivity.kt
- android/app/src/main/java/com/example/myapplication/view/ProfilePageActivity.kt
- android/app/src/main/java/com/example/myapplication/view/SignUpActivity.kt
- android/app/src/main/res/layout/activity_profilepage.xml
I updated the profile page so that It shows enrolled learning spaces of the user. When the user selects an item, it lands on the related learning space.
**Photos:**
`When I click on the gitar I land in the gitar learning space`
> Profile Page enrolled courses are seen and redirected.

- android/app/src/main/java/com/example/myapplication/model/ls_list_element.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace1.kt
- android/app/src/main/java/com/example/myapplication/view/LsListAdapter.kt
- android/app/src/main/res/drawable/ls_card.xml
- android/app/src/main/res/layout/learning_space_1.xml
- android/app/src/main/res/layout/ls_list_item.xml
Since we are gonna display more information about learning spaces, I have updated the page. 
Now, users are able to see not only learning space name, but also its description, owner and creation time.
For displaying more information, waiting for endpoint update from backend.
Description and created at displays are dummy texts for now.
> Learning Space List UI updated

- backend/app/serializers.py
- backend/app/urls.py
- backend/app/views.py
As @ecesrkn suggested from the frontend team, I have implemented a functionality to retrieve username from a given user id. 
It works pretty well. 
Moreover, there is a single line bug fix. A user does not have to upload a profile page. So, I updated it.
> Implemented user_id to user retrieve functionality

- backend/app/models.py
- backend/app/serializers.py
- backend/app/urls.py
- backend/app/views.py
I have implemented endpoints and models for favoreteing and unfavorateing related endpoints. With these endpoints, a user can make a specific learning space her favorite learning space, and also revert it.
> Backend dev favorite learning spaces

- backend/app/serializers.py
- backend/app/views.py
I implemented content editing functionality. On this, you can change the text of a content, and also can change the upVote count.
> Implemented editing content

- android/app/src/main/java/com/example/myapplication/model/add_favorite_data_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace2_add_favorite_receive_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace2_add_favorite_send_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace2_remove_favorite_receive_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace2_remove_favorite_send_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpaceModel.kt
- android/app/src/main/java/com/example/myapplication/model/profile_see_get_receive_model.kt
- android/app/src/main/java/com/example/myapplication/model/user_from_id_receive_model.kt
- android/app/src/main/java/com/example/myapplication/model/user_from_id_send_model.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace2_add_fav_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace2_add_fav_api_call.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace2_remove_fav_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace2_remove_fav_api_call.kt
- android/app/src/main/java/com/example/myapplication/service/user_from_id_api.kt
- android/app/src/main/java/com/example/myapplication/service/user_from_id_api_call.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace2Menu.kt
- android/app/src/main/java/com/example/myapplication/view/ProfilePageActivity.kt
- android/app/src/main/res/layout/activity_profilepage.xml
- Add Favorite back-end connection is made.
- Remove Favorite back-end connection is made.
- User from ID back-end connection is made.
For user:quanex1, image is given by the address:http://3.89.218.253:8000/media/uploads/Ekran_g%C3%B6r%C3%BCnt%C3%BCs%C3%BC_2022-09-28_052625.png
and it is shown in the android as well.
> Profile page image and more back-end connection is made

- android/app/src/main/java/com/example/myapplication/model/list_elements.kt
- android/app/src/main/java/com/example/myapplication/view/HomeActivity.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace1.kt
- android/app/src/main/res/drawable/search_view_bg.xml
- android/app/src/main/res/layout/activity_home.xml
**Issue Description:**
Home page needs to be redesigned. We decided to add search bar to the top of the home page.
* Added Search View on the top of the page.
* Upon clicking it user directed to the search page.
If you click the search view, you are directed to the search page:
> Search bar moved to the home page

- android/app/src/main/java/com/example/myapplication/view/HomeActivity.kt
- android/app/src/main/java/com/example/myapplication/view/HomeViewPager.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace1.kt
- android/app/src/main/java/com/example/myapplication/view/LsListAdapter.kt
- android/app/src/main/res/layout/activity_home.xml
- android/app/src/main/res/layout/ls_list_item.xml
Favorite learning spaces section added to the home page.
API connections will be implemented.
Page design looks like this:
> Favorite learning spaces are listed on home page

- android/app/src/main/java/com/example/myapplication/model/favorite_ls.kt
- android/app/src/main/java/com/example/myapplication/model/favorite_ls_element.kt
- android/app/src/main/java/com/example/myapplication/model/ls_create_model.kt
- android/app/src/main/java/com/example/myapplication/service/favorite_ls_api.kt
- android/app/src/main/java/com/example/myapplication/service/favorite_ls_call.kt
- android/app/src/main/java/com/example/myapplication/view/HomeActivity.kt
- android/app/src/main/java/com/example/myapplication/view/HomeViewPager.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace1.kt
- android/app/src/main/res/layout/activity_home.xml
- android/app/src/main/res/layout/add_learning_space.xml
- android/app/src/main/res/layout/favorite_ls_item.xml
**Issue Description:**
I asked for description, created at and owner field additions to the learning space fields in this [issue](https://github.com/bounswe/bounswe2022group1/issues/712). 
After the endpoint updates, I connected new fields to the list.
Also, updated Learning Space Create function by adding a description input field.
> Learning Space list connections done

- android/app/src/main/java/com/example/myapplication/model/learningSpace3_patch_content_receive_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_patch_content_send_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_patch_note_receive_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_patch_note_send_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_post_note_receive_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_post_note_send_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_see_all_note_receive_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_see_all_note_send_model.kt
- android/app/src/main/java/com/example/myapplication/model/note_model.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_patch_content_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_patch_content_api_call.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_patch_note_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_patch_note_api_call.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_post_note_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_post_note_api_call.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_see_all_note_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_see_all_note_api_call.kt
The following APIs are connected to the android app.
- PATCH /app/note/   (for editting a specific note)
- GET /app/note/      (for getting all notes)
- POST /app/note/     (for creating a specific note)
- PATCH /app/content/    (for editting the content)
> Note and Content api connections are made

- backend/app/views.py
Edit note feature is created. Patch method is implemented in noteAPIview
> Edit note feature is created. Patch method is implemented in noteAPIview

- android/app/src/main/java/com/example/myapplication/view/HomeActivity.kt
- android/app/src/main/java/com/example/myapplication/view/LandingActivity.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace1.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace2Menu.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace2Resources.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace3.kt
- android/app/src/main/java/com/example/myapplication/view/ProfilePageActivity.kt
- android/app/src/main/res/layout/activity_home.xml
- android/app/src/main/res/layout/activity_learning_space2_menu.xml
- android/app/src/main/res/layout/activity_learning_space2_seecontents.xml
- android/app/src/main/res/layout/activity_learning_space3.xml
- android/app/src/main/res/layout/activity_profilepage.xml
- android/app/src/main/res/layout/learning_space_1.xml
In order to increase user experience, favorite learning spaces are already listed on the home page.
We thought that accessing their resources quickly, may increase UX too.
Therefore, resources of favorite Learning Spaces are listed on the home page now.
As swipeView changes its position, resource list is updated according to the displayed learning space on it.
> Resources of Fav. Learning Spaces on the Home Page

- android/app/build.gradle
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_patch_content_receive_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_patch_content_send_model.kt
- android/app/src/main/java/com/example/myapplication/model/note_model.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_patch_content_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_patch_content_api_call.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace2Menu.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace3.kt
I tried to connect notes api with our android app.
> Notes api connection is made.

- android/app/src/main/java/com/example/myapplication/model/learningSpace3_patch_content_send_model.kt
- android/app/src/main/java/com/example/myapplication/view/HomeActivity.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace3.kt
Resource content couldn't be updated since some fields of the request empty.
This bug is fixed, functionality works.
> Resource Update Bug fixed

- android/app/src/main/java/com/example/myapplication/model/note_model.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace3.kt
Notes of the resource page couldn't be retrieved from the backend since api parameters does not match.
Updated fields to the fields seen below, GET request works:
We can now receive notes from the backend:
Also, users are now able to update their notes by clicking the edit button and saving.
> Notes bug fixed, update functionality implemented

- android/app/src/main/java/com/example/myapplication/model/learningSpace3_patch_content_info_send_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_patch_content_send_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_see_all_note_receive_model.kt
- android/app/src/main/java/com/example/myapplication/model/learningSpace3_up_count_send_model.kt
- android/app/src/main/java/com/example/myapplication/model/see_all_note_model.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_patch_content_info_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_patch_content_info_api_call.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_see_all_note_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_see_all_note_api_call.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_up_count_api.kt
- android/app/src/main/java/com/example/myapplication/service/learningSpace3_up_count_api_call.kt
- android/app/src/main/java/com/example/myapplication/view/LearningSpace3.kt
I made the back-end connection with our android app for upvote/downvote functionality in resource page.
> Up vote and down vote functionality is implemented.

- android/app/src/main/java/com/example/myapplication/view/LearningSpace3.kt
Some bug appeared related to empty notes and fixed.
> Empty notes related bug fix

- backend/app/admin.py
- backend/app/views.py
In the issue https://github.com/bounswe/bounswe2022group1/issues/836, I specified that: 
> @omerozdemir1 from the android team informed us that in our current form, a user may favorite the same learning space multiple times. This is not an expected behavior and shouldn't be observed in the production. So, we should fix it asap.
This PR solves that problem.
> Bugfixed the multiple favorites problem

- backend/app/views.py
I implemented a patch method for profileApiView in backend/app/views.py. This method is requested by @kadirgokhann in front-end team in order to update profile picture. Patch method can update about-me and image fileds of Profile model. If one of the parameters is given by patch method only this filed will be updated.
> Patch method to update profile is implemented

- frontend/components/resource/subpages/Main.js
- frontend/styles/globals.css
**To**
@egetaga
**Description**
I added text and image annotations to the resource page. I updated the UI of annotations according to our theme and connected them to the backend. Right now, annotations work as expected with a friendly UI.
**Testing**
User testing
> Frontend Annotations

- backend/app/tests/test_get_id_from_username.py
- backend/app/tests/test_note.py
- backend/app/tests/test_profile.py
Unit tests for profile page, taking notes feature and getting user id from username feature are implemented. With these unit tests get and post methods in app/views.py/profileApiView and app/views.py/noteApiView are tested. Additionally get method in app/views.py/getuseridAPIView is tested. Tests are running without an error.
> Unit tests for profile page, taking notes feature and getting user id

- backend/app/views.py
I solved the bug I mentioned in the issue https://github.com/bounswe/bounswe2022group1/issues/851 below: 
> While dockerizing and deploying the application today early in the morning, I realized that there is a bug in the patch method of the Profile view. I will be fixing it ASAP. 
Please approve the merge.
> Fixed the bug in the patch methd of profileApiView

- frontend/components/edit-resource/EditResourcePage.js
- frontend/components/edit-resource/ResourceEdit.js
- frontend/components/resource/subpages/Main.js
- frontend/components/resource/subpages/PersonalNotes.js
- frontend/pages/edit-resource/[id].js
- frontend/yarn.lock
Everything about the Resource is finalized. New changes are:
- My notes functionality
- Edit Resource page
> Frontend resourcev1 Edit resource & my notes

- backend/app/tests/test_discussion_list.py
- backend/app/tests/test_leave_learning_space.py
Our unit tests regarding the discussion and leave learning space failed due to the changing data model. In this PR, I fixed the unit tests.
> Backend dev test bugfix

- backend/app/tests/test_content_edit.py
- backend/app/tests/test_favorite_unfavorite_ls.py
- backend/app/tests/test_username_from_id.py
I added unit tests for the endpoints I have written: content edit, fav, unfav user from id. They work pretty fine and unit tests are smooth.
> Unittests: content edit, fav, unfav user from id

- annotations/app/tests/test_annotation.py
I added unit tests for get, post, patch, delete functionalities of backend annotation project.
> Tests for get, post, patch, delete for annotation

- backend/app/tests/test_profile.py
Unit test for profileApiView patch method is implemented. Changes can be seen in app/tests/test_profile.py. There was a bug in this method and test were not running. It is running without an error after @egetaga noticed and fixed this bug.
> Unit test for profileApiView patch method is implemented.

- android/app/src/main/java/com/example/myapplication/view/LearningSpace2Menu.kt
In the learning space there was no check if the learning space is added to the favorites.
This functionality implemented
> Check is favorite

- deliverables/CMPE451_Customer_Presentation_Milestone_2/frontend/components/profile/Sidebar.js
- frontend/components/resource/ResourceSidebar.js
- frontend/yarn.lock
There used to be the old logo on the resource sidebar, now it is fixed.
> Frontend resourcev1 - logo fix

- deliverables/CMPE451_Customer_Presentation_Milestone_2/frontend/components/profile/Sidebar.js
- deliverables/CMPE451_Customer_Presentation_Milestone_2/frontend/pages/forgot-password/index.js
- deliverables/CMPE451_Customer_Presentation_Milestone_2/frontend/pages/homepage/index.js
- deliverables/CMPE451_Customer_Presentation_Milestone_2/frontend/pages/login/index.js
- deliverables/CMPE451_Customer_Presentation_Milestone_2/frontend/pages/signup/index.js
- frontend/components/addcontent/ContentAdd.js
- frontend/components/detail/DetailContributors.js
- frontend/components/detail/DetailInfoPage.js
- frontend/components/detail/DetailMain.js
- frontend/components/edit-resource/ResourceEdit.js
- frontend/components/homepage/Forum.js
- frontend/components/homepage/SearchBar.js
- frontend/components/profile/Sidebar.js
- frontend/components/resource/ResourceSidebar.js
- frontend/pages/detail/[id].js
- frontend/pages/forgot-password/index.js
- frontend/pages/homepage/index.js
**To**
@ecesrkn 
**Description**
I improved UI of the homepage and details page. I also, fixed the broken UI of container components of all over the project.
**Testing**
User testing
> update ui of landing page, detail page and fix containers

- android/app/src/main/java/com/example/myapplication/view/ChangePasswordActivity.kt
- android/app/src/main/res/layout/activity_change_password.xml
I added the navigation bar into change password.
> navigation bar added to change password

- README.md
I updated commands and some other instructions which are necessary to build our app.
> Instructions of Frontend App Dependencies Updated

- android/app/src/debug/res/mipmap-anydpi-v26/ic_launcher.xml
- android/app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
- android/app/src/main/AndroidManifest.xml
Fix android resource linking failed error
Set Android Manifest configurations
> Fix linking error, set AndroidManifest configurations

- android/app/src/main/java/com/example/myapplication/view/ChangePasswordActivity.kt
- android/app/src/main/java/com/example/myapplication/view/ProfileCreateActivity.kt
- android/app/src/main/res/layout/activity_change_password.xml
- android/app/src/main/res/layout/activity_profilecreate.xml
navigation bar added to create profile
> navigation bar added to create profile

- backend/app/views.py
Currently, a user can see all notes, but a user can only see his/her own note. This bug is fixed. Owner field in note method is filtered with get method in app/views.py/noteApiView.
> Currently, a user can see all notes, but a user can only see his/her own note. I fixed this bug.

- android/app/src/debug/res/mipmap-anydpi-v26/ic_launcher.xml
- android/app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/myapplication/view/ProfileCreateActivity.kt
- android/app/src/main/res/layout/activity_profilecreate.xml
Reverts bounswe/bounswe2022group1#894
> Revert "navigation bar added to create profile"

- android/app/src/main/java/com/example/myapplication/view/ChangePasswordActivity.kt
- android/app/src/main/res/layout/activity_change_password.xml
Reverts bounswe/bounswe2022group1#888
> Revert "navigation bar added to change password"

- frontend/components/detail/DetailMain.js
**There is a bug while clicking on join/leave button:** 
It was not shown on page without clicking twice to this button. I solved this problem.
> Clicking Twice Bug Resolved

- deliverables/CMPE451_Customer_Presentation_Milestone_3/group_milestone_review.md
Added group milestone review for final milestone, includes group review and individual work
> Added group milestone review for final milestone

- deliverables/CMPE451_Customer_Presentation_Milestone_3/group_milestone_review.md
Annotations are missing in android, not in frontend. Fixed it.
> Correction about annotations.
